version: "3"

services:
  mongo:
    image: mongo
  postgres:
    image: postgres
    restart: always
    ports:
        - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  neo:
    image: neo4j
    ports:
      - 7474:7474 
      - 7687:7687
  redis: 
    image: redis
  notebook:
    build: notebook/
    ports:
      - 8888:8888
    volumes:
       - ./:/home/jovyan/work/data
    environment:
      - GRANT_SUDO=yes
      